name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: [self-hosted, static-web]
    steps:
      - uses: actions/checkout@v3
      - name: Build static site
        run: echo 'Building the static website...'
